services:
  jobmngrd:
    image: ${KOMPIRA_IMAGE_NAME:-kompira.azurecr.io/kompira-enterprise}:${KOMPIRA_IMAGE_TAG:-latest}
    hostname: jm-${HOSTNAME:?HOSTNAME must be set}
    init: true
    environment:
      AMQP_URL: ${AMQP_URL:-amqp://guest:guest@rabbitmq:5672}
      TZ: ${TZ:-Asia/Tokyo}
      LOGGING_NAME: jobmngrd
      LOGGING_STREAM: ${JOBMNGRD_LOGGING_STREAM:-${LOGGING_STREAM:-true}}
      LOGGING_LEVEL: ${JOBMNGRD_LOGGING_LEVEL:-${LOGGING_LEVEL:-INFO}}
      LOGGING_DIR: ${JOBMNGRD_LOGGING_DIR:-${LOGGING_DIR:-/var/log/kompira}}
      LOGGING_BACKUP: ${JOBMNGRD_LOGGING_BACKUP:-${LOGGING_BACKUP:-7}}
      LOGGING_WHEN: ${JOBMNGRD_LOGGING_WHEN:-${LOGGING_WHEN:-MIDNIGHT}}
      LOGGING_INTERVAL: ${JOBMNGRD_LOGGING_INTERVAL:-${LOGGING_INTERVAL:-1}}
    configs:
      - source: kompira-config
        target: /opt/kompira/kompira.conf
    volumes:
      - ${KOMPIRA_VAR_DIR:-kompira_var}:/var/opt/kompira
      - ${KOMPIRA_LOG_DIR:-kompira_log}:/var/log/kompira
    extra_hosts:
      - host.docker.internal:host-gateway
    command: ["jobmngrd"]
    ulimits:
      nproc: 65535
      nofile: 65535
configs:
  kompira-config:
    file: ../../configs/kompira.conf
volumes:
  kompira_var:
  kompira_log:
