services:
  nginx:
    image: registry.hub.docker.com/library/nginx:1.27-alpine
    hostname: nx-${HOSTNAME}
    environment:
      - TZ=${TZ:-Asia/Tokyo}
      - NGINX_ENVSUBST_FILTER=^KOMPIRA
    configs:
      # MEMO: /etc/nginx/templates/*.template は起動時に環境変数が展開されて /etc/nginx/conf.d/* に書き出される
      - source: nginx-config
        target: /etc/nginx/templates/default.conf.template
    volumes:
      - ${KOMPIRA_VAR_DIR:-kompira_var}:/var/opt/kompira
      - ${KOMPIRA_SSL_DIR:-../../ssl}:/etc/nginx/ssl:ro
    ports:
      - "80:80"
      - "443:443"
configs:
  nginx-config:
    file: ../../configs/nginx.conf
volumes:
  kompira_var:
