services:
  postgres:
    # MEMO: potgrsql のメジャーバージョンを変更するときは PGDATA 領域のボリューム名も変更すること
    image: registry.hub.docker.com/library/postgres:16.3-alpine
    hostname: db-${HOSTNAME}
    environment:
      POSTGRES_PASSWORD: kompira
      POSTGRES_USER: kompira
      TZ: ${TZ:-Asia/Tokyo}
    volumes:
      - ${PGDATA:-kompira_pg16}:/var/lib/postgresql/data
volumes:
  # MEMO: postgresql のメジャーバージョンごとにボリュームを分けておく
  kompira_pg16:
