services:
  rabbitmq:
    image: registry.hub.docker.com/library/rabbitmq:3.13-alpine
    hostname: mq-${HOSTNAME:?HOSTNAME must be set}
    environment:
      RABBITMQ_DATA_DIR: /var/lib/rabbitmq
      TZ: ${TZ:-Asia/Tokyo}
    configs:
      - source: bootstrap-rabbitmq
        target: /run/bootstrap-rabbitmq.sh
      - source: rabbitmq-config-auth
        target: /etc/rabbitmq/conf.d/20-auth.conf
      - source: rabbitmq-config-ssl
        target: /etc/rabbitmq/conf.d/30-ssl.conf
    volumes:
      - /var/lib/rabbitmq
      - ${KOMPIRA_SSL_DIR:-../../ssl}:/run/.kompira_ssl:ro
    command:
      # MEMO: 必要な前処理を行なって rabbitmq-server を起動する bootstrap-rabbitmq.sh スクリプトを実行する
      - /bin/sh
      - /run/bootstrap-rabbitmq.sh
    ports:
      # MEMO: 外部には AMQPS ポートだけオープンしている (AMQP 接続を許可する場合は 5672 もオープンにする)
      - "5671:5671"
configs:
  bootstrap-rabbitmq:
    file: ../../scripts/bootstrap-rabbitmq.sh
  rabbitmq-config-auth:
    file: ../../configs/rabbitmq-auth.conf
  rabbitmq-config-ssl:
    file: ../../configs/rabbitmq-ssl.conf
